### ISSUE TITLE
Connecting without a mapDispatchToProps function should inject dispatch to props to match react's behavior.

### ISSUE THREAD

**Issue by Mduro** [Roblox/roact-rodux#18]
In essence, if mapDispatchToProps isn't specified, then the following function should be mapDispatchToProps instead:

```
function mapDispatchToProps(dispatch)
   return { dispatch = dispatch }
end
```

This would match the behavior that [react](https://github.com/reduxjs/react-redux/blob/master/docs/api.md#connect) has:

> If you do not supply your own mapDispatchToProps function or object full of action creators, the default mapDispatchToProps implementation just injects dispatch into your component’s props.

**Comment by ZoteTheMighty** [comment]
I actually prefer to keep this explicit. Having roact-rodux silently inject an additional prop that wasn't asked for seems problematic to me, especially since it could break existing code in subtle ways.

What's the reasoning for adding this default behavior? Do you find yourself implementing that version mapDispatchToProps often? We try to avoid making changes just to match React, but I'm sure they have reasons for doing it this way too.

**Comment by Mduro** [comment]
After mulling about this for a bit, I realized that calling dispatch directly inside the component isn't the best solution for my use-case.

I was writing a "list" component composed of several buttons, and I want each button to dispatch a different action. I was originally passing the action to the button's props and then dispatching those actions inside the button component. It just occurred to me that I could also map the dispatches to props in the list component itself, and I could then pass these dispatches to the button's props, which would call these dispatches when activated. This method is more compact and doesn't restrict the button to only being able to accept actions (it can now accept callbacks, too.)

I'll be closing this issue now.
