### ISSUE TITLE
Prop changes don't trigger mapStoreToProps

### ISSUE THREAD

**Issue by LPGhatguy** [Roblox/roact-rodux#2]
Consider a component using Roact-Rodux whose `mapStoreToProps` selector uses the little-known second parameter of `props`:

```lua
local function MyComponent(props)
    -- doesn't matter
end

MyComponent = RoactRodux.connect(function(store, props)
    -- Our selector just pulls whatever key you want out of the store
    return {
        value = store:GetState()[props.storeKey]
    }
end)
```

When props update, the predicate won't be invoked again, but the component will be able to observe that `storeKey` changed!

**Comment by AmaranthineCodices** [comment]
This is kind of tricky to fix in a performant / correct way in the current version of Roact.

* If we intercept the update in `willUpdate`, we will throw, because we can't `setState` in `willUpdate`.
* If we intercept the update in `didUpdate`, we've just re-rendered the component twice (once in response to the property change, and once in response to the state change from re-computing the store props), *and* the component will have observed a property change without a corresponding state change.

React-Redux appears to be handling this using `componentWillReceiveProps`, which Roact doesn't implement.

**Comment by LPGhatguy** [comment]
Thanks for doing that research -- I found the react-redux source code kind of hard to read when I took a peak last.
