### ISSUE TITLE
Importing with Rotriever causes unit tests to fail

### ISSUE THREAD

**Issue by Kylaaa** [Roblox/roact-rodux#22]
The Rotriever.toml file imports Roact, but the tests expect that Rodux is also imported.

The following tests fail with the same messages (TestService: Error during planning: Rodux is not a valid member of Folder) :
- getStore.spec.lua
- connect.spec.lua
- StoreProvider.spec.lua

Please update the toml file to include Rodux.

**Comment by LPGhatguy** [comment]
We're waiting for development dependency support in Rotriever before we add Rodux to Roact-Rodux, since at runtime it doesn't actually depend on Rodux.

It sounds a bit like you're trying to run the tests of dependencies installed via Rotriever. That's pretty strange and is unsupported, since it's possible for a project to need some dependencies only for testing, like TestEZ!
